spring.application.name=coreService

server.port=8080

server.address=localhost


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=gday2051001~


spring.datasource.username=postgres
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-swallow-size=20MB


download.folder=src/main/resources/static/img/gday_test_file/


spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.use_sql_comments= true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

ftp.server.url=petcineftp.com
ftp.port=22
ftp.user=root
ftp.pwd=gday2051001~
ftp.folder=/usr/share/doc/HTML/images/
ftp.return.url=https://petcineftp.com/images/

back.ftp.server.url=192.168.0.90

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=10000

